---
title: "First steps"
author: "Jakob Uhl"
date: "3 5 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages}

install.packages("shiny")
install.packages("tidyverse")
install.packages("shinydashboard")

library(shiny)
library(tidyverse)
library(shinydashboard)

```

```{r dashboard elements try out}

ui <- dashboardPage(
  dashboardHeader(title = "Testseite"),
  dashboardSidebar(),
  dashboardBody(
    box(plotOutput("correlation_plot"), width = 6),
    box(plotOutput("correlation_plot_2"), width = 6),
    infoBox(
      "Approval Rating", "60%", icon = icon("line-chart"), color = "green",
      fill = TRUE
    ),valueBox(
      uiOutput("orderNum"), "New Orders", icon = icon("credit-card"),
      href = "http://google.com"
    ),
    fluidRow(
    box(status = "primary",
      sliderInput("orders", "Orders", min = 1, max = 2000, value = 650),
      selectInput("progress", "Progress",
        choices = c("0%" = 0, "20%" = 20, "40%" = 40, "60%" = 60, "80%" = 80,
                    "100%" = 100)
      )
    ),
  )
))

server <- function(input, output) {
  output$correlation_plot <- renderPlot({ggplot(iris, aes(x=Sepal.Length, y=Sepal.Width))+ geom_point()})
  output$correlation_plot_2 <- renderPlot({ggplot(iris, aes(x=Sepal.Length, y=Petal.Length, colour = Species))+ geom_point()})
}

shinyApp(ui, server)

```

```{r data Affektiva}

faceReaderSample <- read.csv(file = "ExportMerge.csv")



faceReaderSample_short <- faceReaderSample[-c(1:25,206:209),]
names(faceReaderSample_short) <- (faceReaderSample[23,])
faceReaderSample_short$EventSource = NULL

ggplot(data = faceReaderSample_short, aes(x = Timestamp, y = Joy, color = Respondent)) +
  geom_point(size = 0.1) + geom_smooth(aes(group = factor(Respondent)), size =1.5, alpha = 0.2, level = 0.95, formula = y ~ poly(x,10), method = "lm", se = F) + 
  theme_minimal() + 
  theme(axis.text.y.left =  element_blank()) +
  theme(axis.text.x =  element_blank())+
  ylab(label = "Joy") 


plot(faceReaderSample_short$Timestamp, faceReaderSample_short$Joy)

```
